version: '3.8'
services:
  postgres:
    image: "postgres:15"
    container_name: postgres
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: scrapper
      POSTGRES_PASSWORD: scrapper
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:\\wsl$\docker-desktop-data\data\docker\volumes
    restart: always
    networks:
      - backend
  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgres
    command:
      - --hub-mode=off
      - --changelog-file=src/main/resources/migrations/master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5433/scrapper
      - --username=scrapper
      - --password=scrapper
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq_state:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  postgres-data:

networks:
  backend: {}