/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Link;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record7<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK.ID</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK.ID</code>.
     */
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINK.URL</code>.
     */
    public void setUrl(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINK.LAST_UPDATED</code>.
     */
    public void setLastUpdated(@Nullable LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINK.LAST_UPDATED</code>.
     */
    @Nullable
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>LINK.LAST_CHECKED</code>.
     */
    public void setLastChecked(@Nullable LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINK.LAST_CHECKED</code>.
     */
    @Nullable
    public LocalDateTime getLastChecked() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>LINK.LAST_CHECKED_WHEN_WAS_UPDATED</code>.
     */
    public void setLastCheckedWhenWasUpdated(@Nullable LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>LINK.LAST_CHECKED_WHEN_WAS_UPDATED</code>.
     */
    @Nullable
    public LocalDateTime getLastCheckedWhenWasUpdated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>LINK.LAST_COMMIT_DATE</code>.
     */
    public void setLastCommitDate(@Nullable LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>LINK.LAST_COMMIT_DATE</code>.
     */
    @Nullable
    public LocalDateTime getLastCommitDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>LINK.LAST_ANSWER_DATE</code>.
     */
    public void setLastAnswerDate(@Nullable LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>LINK.LAST_ANSWER_DATE</code>.
     */
    @Nullable
    public LocalDateTime getLastAnswerDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row7<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row7<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Link.LINK.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Link.LINK.URL;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field3() {
        return Link.LINK.LAST_UPDATED;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field4() {
        return Link.LINK.LAST_CHECKED;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field5() {
        return Link.LINK.LAST_CHECKED_WHEN_WAS_UPDATED;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field6() {
        return Link.LINK.LAST_COMMIT_DATE;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field7() {
        return Link.LINK.LAST_ANSWER_DATE;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getUrl();
    }

    @Override
    @Nullable
    public LocalDateTime component3() {
        return getLastUpdated();
    }

    @Override
    @Nullable
    public LocalDateTime component4() {
        return getLastChecked();
    }

    @Override
    @Nullable
    public LocalDateTime component5() {
        return getLastCheckedWhenWasUpdated();
    }

    @Override
    @Nullable
    public LocalDateTime component6() {
        return getLastCommitDate();
    }

    @Override
    @Nullable
    public LocalDateTime component7() {
        return getLastAnswerDate();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getUrl();
    }

    @Override
    @Nullable
    public LocalDateTime value3() {
        return getLastUpdated();
    }

    @Override
    @Nullable
    public LocalDateTime value4() {
        return getLastChecked();
    }

    @Override
    @Nullable
    public LocalDateTime value5() {
        return getLastCheckedWhenWasUpdated();
    }

    @Override
    @Nullable
    public LocalDateTime value6() {
        return getLastCommitDate();
    }

    @Override
    @Nullable
    public LocalDateTime value7() {
        return getLastAnswerDate();
    }

    @Override
    @NotNull
    public LinkRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value2(@NotNull String value) {
        setUrl(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value3(@Nullable LocalDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value4(@Nullable LocalDateTime value) {
        setLastChecked(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value5(@Nullable LocalDateTime value) {
        setLastCheckedWhenWasUpdated(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value6(@Nullable LocalDateTime value) {
        setLastCommitDate(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value7(@Nullable LocalDateTime value) {
        setLastAnswerDate(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord values(@NotNull Long value1, @NotNull String value2, @Nullable LocalDateTime value3, @Nullable LocalDateTime value4, @Nullable LocalDateTime value5, @Nullable LocalDateTime value6, @Nullable LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    @ConstructorProperties({ "id", "url", "lastUpdated", "lastChecked", "lastCheckedWhenWasUpdated", "lastCommitDate", "lastAnswerDate" })
    public LinkRecord(@NotNull Long id, @NotNull String url, @Nullable LocalDateTime lastUpdated, @Nullable LocalDateTime lastChecked, @Nullable LocalDateTime lastCheckedWhenWasUpdated, @Nullable LocalDateTime lastCommitDate, @Nullable LocalDateTime lastAnswerDate) {
        super(Link.LINK);

        setId(id);
        setUrl(url);
        setLastUpdated(lastUpdated);
        setLastChecked(lastChecked);
        setLastCheckedWhenWasUpdated(lastCheckedWhenWasUpdated);
        setLastCommitDate(lastCommitDate);
        setLastAnswerDate(lastAnswerDate);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.Link value) {
        super(Link.LINK);

        if (value != null) {
            setId(value.getId());
            setUrl(value.getUrl());
            setLastUpdated(value.getLastUpdated());
            setLastChecked(value.getLastChecked());
            setLastCheckedWhenWasUpdated(value.getLastCheckedWhenWasUpdated());
            setLastCommitDate(value.getLastCommitDate());
            setLastAnswerDate(value.getLastAnswerDate());
        }
    }
}
