server:
  port: 8080

app:
  database-access-type: jdbc
  use-queue: true
  scheduler:
    interval: 60000 #1min
    check: 600000 #10min
  rabbitMQNames:
    queue-name: directQueueYml
    exchange-name: directExchangeYml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

client:
    url:
      github: https://api.github.com/repos
      stackoverflow: https://api.stackexchange.com/2.3/questions
      bot: http://localhost:8081

spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/scrapper
    username: scrapper
    password: scrapper
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:migrations/master.xml