server:
  port: 8081

app:
  token: newToken
  use-queue: true
  scrapper-queue:
    name: directQueueYml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

client:
  url:
    scrapper: http://localhost:8080