server:
  port: 8081

app:
  token: 6279920538:AAHU3FTsRBZmfzQBK9bXACu0nII0_KD6R00

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

client:
  url:
    scrapper: http://localhost:8080