server:
  port: 8081

app:
  token: newToken
  use-queue: true
  rabbitMQNames:
    queue-name: directQueueYml
    exchange-name: directExchangeYml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

client:
  url:
    scrapper: http://localhost:8080